# -*- coding: utf-8 -*-
"""Stable_Diffusion.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TkjO3M4v5wlqiUUiJrpLADsJUiMlcMoi
"""

!nvidia-smi

!pip install albumentations==0.4.3
!pip install diffusers
!pip install opencv-python==4.1.2.30
!pip install pudb==2019.2
!pip install imageio==2.9.0
!pip install imageio-ffmpeg==0.4.2
!pip install pytorch-lightning
!pip install omegaconf==2.1.1
!pip install test-tube>=0.7.5
!pip install streamlit>=0.73.1
!pip install einops==0.3.0
!pip install torch-fidelity==0.3.0
!pip install transformers==4.19.2
!pip install kornia
!pip install -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
!pip install -e git+https://github.com/openai/CLIP.git@main#egg=clip
!pip install invisible-watermark

"""# not installed とでるが、[参考サイト](https://gammasoft.jp/blog/simple-way-to-try-stable-diffusion/#download-model)によると、問題ないらしいので無視する。"""

!pip check

"""# Stable DiffusionのSourceCodeをダウンロードする"""

!git clone https://github.com/CompVis/stable-diffusion.git

# Commented out IPython magic to ensure Python compatibility.
# %cd stable-diffusion

"""# 以下のコマンドでセットアップを行う"""

!pip install -e .

!python scripts/txt2img.py  --prompt "Flying Cat" \
                            --plms \
                            --ckpt "/content/drive/MyDrive/Colab Notebooks/model/v1-5-pruned-emaonly.ckpt" \
                            --skip_grid \
                            --n_samples 3